# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

windowrule = match:class ^(.*\.exe)$, tile on
windowrule = match:title ^(.*Ghidra.*)$, tile on
windowrule = match:class ^(.*Minecraft.*)$, tile on

windowrule = match:class firefox, workspace 1
windowrule = match:title tty1, workspace 2
windowrule = match:title tty2, workspace 3
windowrule = match:class YouTube Music Desktop App, workspace 4
windowrule = match:class org.mozilla.Thunderbird, workspace 5
windowrule = match:title Unlock Login Keyring, workspace 1

workspace= name:1, monitor:HDMI-A-1 
workspace= name:2, monitor:HDMI-A-1 
workspace= name:3, monitor:HDMI-A-1 
workspace= name:4, monitor:eDP-1 
workspace= name:5, monitor:eDP-1

windowrule = match:class flameshot, move 0 0
windowrule = match:class flameshot, float on
windowrule = match:title ^(.*Cube.*)$, float on
windowrule = match:title ^(.*Cube.*)$, center on
windowrule = match:class flameshot, fullscreen_state 3 3
windowrule = match:class flameshot, pin on

windowrule = match:class ^(xdg-desktop-portal-gtk)$, float on
windowrule = match:class ^(xdg-desktop-portal-gtk)$, size 60% 70%
windowrule = match:class ^(xdg-desktop-portal-gtk)$, center on

windowrule = match:class ^(org.kde.kdialog)$, float on
windowrule = match:class ^(org.kde.kdialog)$, size 60% 70%
windowrule = match:class ^(org.kde.kdialog)$, center on
