# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

windowrulev2 = tile, class:^(.*\.exe)$
windowrulev2 = tile, title:^(.*Ghidra.*)$
windowrulev2 = tile, title:^(.*JFLAP.*)$
