# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

windowrule = match:class ^(.*\.exe)$, tile on
windowrule = match:title ^(.*Ghidra.*)$, tile on
windowrule = match:class ^(.*Minecraft.*)$, tile on

windowrule = match:class firefox, workspace 1
windowrule = match:title tty1, workspace 2
windowrule = match:title tty2, workspace 3
windowrule = match:class Spotify, workspace 4
windowrule = match:class org.mozilla.Thunderbird, workspace 5

workspace= name:1, monitor:HDMI-A-1 
workspace= name:2, monitor:HDMI-A-1 
workspace= name:3, monitor:HDMI-A-1 
